// Generated by Xata Codegen 0.28.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Profile",
    columns: [
      { name: "firstname", type: "string" },
      { name: "lastname", type: "string" },
      { name: "dogname", type: "string" },
      { name: "dogbreed", type: "string" },
      { name: "dogweight", type: "string" },
      { name: "dogage", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Profile = InferredTypes["Profile"];
export type ProfileRecord = Profile & XataRecord;

export type DatabaseSchema = {
  Profile: ProfileRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Todd-Peltzer-s-workspace-5e5e54.us-west-2.xata.sh/db/we-feed-raw",
    apiKey: 'xau_vjg4TvtOvnifujL4LStP25cQuPj1XU3Xc'
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options, enableBrowser: true }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
